apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipes.fullname" . }}-db
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "recipes.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}-db